Improve adult parallelization options
mitre/growthcleanr pull request #28
Opened 2021-06-03 17:13 UTC by delosh653

Improves adult parallelization.

2021-06-07 15:52 UTC, dchud commented
Initial results suggest that this current approach is not as efficient as a hard data split.

2021-06-09 17:51 UTC, dchud requested changes
Another issue, when I run:

```bash
Rscript exec/gcdriver.R --sdrecenter nhanes --weightcap 400 --numbatches 6 --adult_split 50 ../gc-test-samples/sa100kb.csv ../gc-test-results/202106/sa100kb-clean-6b-50s.csv
```

...that is, using the 100k-b sample, the script quickly returns:

```R
Error in bmerge(i, x, leftcols, rightcols, roll, rollends, nomatch, mult,  :
  Incompatible join types: i.subjid is type integer64 but x.subjid is type double and contains fractions
Calls: merge -> merge.data.table -> [ -> [.data.table -> bmerge
Execution halted
```

Sorry, haven't dug in to where this is happening yet.

2021-06-09 17:51 UTC, dchud commented on exec/gcdriver.R
> +  flag = Inf,
Ran into an issue here:

```R
Error in parse_args(parser) :
  'list' object cannot be coerced to type 'logical'
```

Works if I change this to:

```R
parser <- add_argument(
  parser,
  "--adult_split",
  type = "numeric",
  default = Inf,
  help = "Number of splits to run data on"
)
```

2021-06-09 17:51 UTC, dchud commented on exec/gcdriver.R
> +df_out <- df_out[, -c("id_order", "entry")]
Looks like if you run this without `adult_split` set, this line errors out as the columns haven't been added:

```R
Warning message:
In `[.data.table`(df_out, , -c("id_order", "entry")) :
  column(s) not removed because not found: [entry]
```

2021-06-10 20:07 UTC, delosh653 commented on exec/gcdriver.R
> +  flag = Inf,
Added this, thanks!

2021-06-10 20:08 UTC, delosh653 commented on exec/gcdriver.R
> +df_out <- df_out[, -c("id_order", "entry")]
Thanks for catching, pushed  a fix!

2021-06-10 20:11 UTC, delosh653 commented
> 
> 
> Another issue, when I run:
> 
> ```shell
> Rscript exec/gcdriver.R --sdrecenter nhanes --weightcap 400 --numbatches 6 --adult_split 50 ../gc-test-samples/sa100kb.csv ../gc-test-results/202106/sa100kb-clean-6b-50s.csv
> ```
> 
> ...that is, using the 100k-b sample, the script quickly returns:
> 
> ```r
> Error in bmerge(i, x, leftcols, rightcols, roll, rollends, nomatch, mult,  :
>   Incompatible join types: i.subjid is type integer64 but x.subjid is type double and contains fractions
> Calls: merge -> merge.data.table -> [ -> [.data.table -> bmerge
> Execution halted
> ```
> 
> Sorry, haven't dug in to where this is happening yet.

I suspect this was due to coercion of subject ids to numeric. I pushed a (hopeful) fix, let me know if it works!

2021-06-11 21:29 UTC, dchud approved these changes

2021-06-11 23:52 UTC, merged